# Generated by Django 5.2.8 on 2025-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('marked', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
